export class Reporte{
    idpersona!: number;
    nombre!: String;
    apellido!: String;
    correo! : String;
    celular!: number;
    dnipasaporte!: number;
    codigo_paciente!: number;
    edad!: number;
    estado!: number;
    fecha1! : String;
    hora1! : String;
    url1! : String;
    fecha2! : String;
    hora2! : String;
    url2! : String;
    fecha3! : String;
    hora3! : String;
    url3! : String;
    obs_generales1! :String;
    antecedentes1! :String;
    problem_actual1! :String;
    acciones_realiz1! :String;
    conclusiones1! :String;
    recomendaciones1! :String;
    obs_generales2! :String;
    antecedentes2! :String;
    problem_actual2! :String;
    acciones_realiz2! :String;
    conclusiones2! :String;
    recomendaciones2! :String;
    obs_generales3! :String;
    antecedentes3! :String;
    problem_actual3! :String;
    acciones_realiz3! :String;
    conclusiones3! :String;
    recomendaciones3! :String;
    idpsicologo!: number;
}